import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./primitiveui.css";
import Providers from "@/lib/providers";
import { Navbar } from "./ui/Navbar";
import { worker } from "./api/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Start our mock API server
  // await worker.start({ onUnhandledRequest: "bypass" });

  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          {children}
        </body>
      </html>
    </Providers>
  );
}
