import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./primitiveui.css";
import StoreProvider from "./ui/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Redux Fundamentals Example",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <nav>
            <section>
              <h1>Redux Fundamentals Example</h1>
            </section>
          </nav>
          <main>
            <section className="medium-container">{children}</section>
          </main>
        </body>
      </html>
    </StoreProvider>
  );
}
